#display repo config, may need to refine
CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y
CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI=y
# General touch driver: provides touch_CHSC6417.h needed by src/lvgl/lvgl_port/lv_port_indev.c
CONFIG_REALTEK_TOUCH_CHSC6417=y
CONFIG_REALTEK_TOUCH_CHSC6417_ZEPHYR=y
CONFIG_REALTEK_KEY_BUTTON_8773G_ZEPHYR=y
CONFIG_REALTEK_BUILD_LVGL=y
CONFIG_LV_CONF_SKIP=n

#app 1, lvgl demo, such as benchmark and demo widget
CONFIG_REALTEK_BUILD_LVGL_SIMPLE_DEMO=y
CONFIG_REALTEK_BUILD_LVGL_RTK_DEMO=y
CONFIG_LV_BUILD_DEMOS=y
CONFIG_LV_USE_DEMO_BENCHMARK=y
CONFIG_LV_USE_DEMO_MUSIC=y
CONFIG_LV_USE_DEMO_STRESS=y
CONFIG_LV_USE_DEMO_WIDGETS=y
#app 2, lvgl watch demo
CONFIG_REALTEK_BUILD_GUI_410_502_LVGL_DEMO=n
#app 3, squareline watch demo
CONFIG_REALTEK_BUILD_GUI_410_502_SQUARELINE_DEMO=n
#lvgl lite3d
CONFIG_REALTEK_BUILD_LVGL_LITE3D=y
CONFIG_REALTEK_BUILD_LVGL_LITE3D_8773G_ZEPHYR_LIB=y
#lvgl freetype
CONFIG_REALTEK_BUILD_FREETYPE_SRC=n
CONFIG_FREETYPE_USE_LVGL_PORT=n

#hardware device config
CONFIG_GPIO=y
CONFIG_GPIO_ENABLE_DISABLE_INTERRUPT=y
CONFIG_I2C=y

# Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=n
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

#
# C++ Language Support
#
CONFIG_CPP=y
CONFIG_STD_CPP11=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y

# end of C++ Language Support
