/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

/* Define to prevent recursive inclusion */
#ifndef _UPAY_SERVICE_H_
#define _UPAY_SERVICE_H_

#ifdef __cplusplus
extern "C"  {
#endif      /* __cplusplus */

/* Add Includes here */
#include "bt_gatt_svc.h"

/* upay service uuid */
#define GATT_UUID_UPAY_SERVICE        0x3802
#define GATT_UPAY_CHARACTERISTIC      0x4a02
#define GATT_UUID_CHAR_DESCRIPTOR_ALIPAY    0x4b02
/*attribut index*/
#define INDEX_UPAY_WRITE                  0x02
#define INDEX_UPAY_READ                   0x02
#define INDEX_UPAY_NOTIFY                 0x02
#define INDEX_UPAY_CHAR_CCCD              0x03
#define INDEX_UPAY_CHAR_DESCRIPTOR        0x04

#define UPAY_NOTIFY_INDICATE_ENABLE             1
#define UPAY_NOTIFY_INDICATE_DISABLE            2

#define UPAY_READ                                  1
#define UPAY_WRITE                                 1

#define GATT_MSG_UPAY_SERVER_READ              0x00
#define GATT_MSG_UPAY_SERVER_WRITE             0x01
#define GATT_MSG_UPAY_SERVER_CCCD_UPDATE       0x02

typedef uint16_t (*P_FUN_UPAY_SERVER_APP_CB)(uint8_t type, void *p_data);
typedef struct
{
    uint8_t opcode;
    T_WRITE_TYPE write_type;
    uint16_t len;
    uint8_t *p_value;
} T_UPAY_WRITE_MSG;

typedef union
{
    uint8_t notification_indification_index;
    uint8_t read_value_index;
    T_UPAY_WRITE_MSG write;
} T_UPAY_UPSTREAM_MSG_DATA;

typedef struct
{
    uint8_t                  conn_id;
    T_SERVER_ID              service_id;
    T_UPAY_UPSTREAM_MSG_DATA msg_data;
} T_UPAYS_CALLBACK_DATA;

/**
 * @brief       Send notify upay data .
 *
 * @param[in]   conn_id  Connection id.
 * @param[in]   service_id  Service id.
 * @param[in]   battery_level  Battery level value.
 * @return Operation result.
 * @retval true Operation success.
 * @retval false Operation failure.
 * \endcode
 */
bool upay_data_notify(uint16_t conn_handle, uint16_t cid, uint8_t *data, uint32_t data_len);
/**
  * @brief Add upay service to the BLE stack database.
  *
  * @param[in]   app_cb  Callback when service attribute was read, write or cccd update.
  * @param[in]   send_cb  send data complete callback.
  * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval others Service id assigned by stack.
  *
  */
T_SERVER_ID upay_reg_srv(P_FUN_UPAY_SERVER_APP_CB app_cb, P_FUN_GATT_EXT_SEND_DATA_CB send_cb);


#ifdef __cplusplus
}
#endif

#endif /* _UPAY_SERVICE_CONFIG_H_ */
