manifest:
  version: '1.2'
  remotes:
  - name: fork
    url-base: https://github.com/rtkconnectivity
  defaults:
    remote: fork
  projects:
  - name: zephyr
    repo-path: rtl87x3g-zephyr
    revision: aed0a36ed1e1a16eef143576716d1cd1e124310f
    path: zephyrproject/zephyr
    west-commands: scripts/west-commands.yml
  - name: cmsis
    url: https://github.com/zephyrproject-rtos/cmsis.git
    revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
    path: zephyrproject/modules/hal/cmsis
    groups:
    - hal
  - name: fatfs
    url: https://github.com/zephyrproject-rtos/fatfs.git
    revision: 427159bf95ea49b7680facffaa29ad506b42709b
    path: zephyrproject/modules/fs/fatfs
    groups:
    - fs
  - name: mbedtls
    url: https://github.com/zephyrproject-rtos/mbedtls.git
    revision: a78176c6ff0733ba08018cba4447bd3f20de7978
    path: zephyrproject/modules/crypto/mbedtls
    groups:
    - crypto
  - name: tinycrypt
    url: https://github.com/zephyrproject-rtos/tinycrypt.git
    revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
    path: zephyrproject/modules/crypto/tinycrypt
    groups:
    - crypto
  - name: honeygui
    repo-path: HoneyGUI
    revision: ebe9378874810fd86c239f1def9488878257be6f
    path: zephyrproject/modules/honeygui
  - name: lvgl
    repo-path: lvgl
    revision: 491c579e0dafb49917100d45510e0d741a89d116
    path: zephyrproject/modules/lvgl
  - name: hal_realtek
    repo-path: hal_realtek
    revision: a77b3986d77a134bd142fbf99100d9f1e231b2ac
    path: zephyrproject/modules/hal/realtek
  - name: display
    repo-path: display
    revision: 44361a88076dd08c72687e2fea6d17d3843526c1
    path: zephyrproject/modules/display
  self:
    path: zephyrproject/realtek-app
    userdata:
      product: watch
      version: v1.14.3.2
