CONFIG_REALTEK_SUBSYS_USB=y
CONFIG_REALTEK_SUBSYS_AUDIO=y
CONFIG_REALTEK_SUBSYS_SYSM=y
CONFIG_REALTEK_SUBSYS_REMOTE=y
CONFIG_REALTEK_SUBSYS_BTM=y

CONFIG_REALTEK_USB_AUDIO_ENABLE=n
CONFIG_REALTEK_USB_HID_MOUSE_ENABLE=n
CONFIG_REALTEK_USB_HID_KEYBOARD_ENABLE=y

# Needed by src/key/gpio_key.c
CONFIG_GPIO=y
