/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

/* Define to prevent recursive inclusion */
#ifndef _WALKIE_TALKIE_GATT_SVC_H_
#define _WALKIE_TALKIE_GATT_SVC_H_

#ifdef  __cplusplus
extern "C" {
#endif      /* __cplusplus */

/* Add Includes here */
#include "bt_gatt_svc.h"


/** @defgroup Walkie talkie GATT Service
  * @brief Walkie talkie service
  * @details
  * @{
  */

/*============================================================================*
 *                         Macros
 *============================================================================*/

#define GATT_UUID128_WALKIE_TALKIE_SERVICE          0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x02, 0x01, 0x00, 0x00
#define GATT_UUID128_WALKIE_TALKIE_CONTROL_POINT    0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x02, 0x02, 0x00, 0x00
#define GATT_UUID128_WALKIE_TALKIE_WRITE            0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x02, 0x03, 0x00, 0x00
#define GATT_UUID128_WALKIE_TALKIE_NOTIFY           0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x02, 0x04, 0x00, 0x00

#define GATT_MSG_WTS_SERVER_WRITE_CONTROL_POINT     0x00
#define GATT_MSG_WTS_SERVER_WRITE                   0x01

/*============================================================================*
 *                              Types
 *============================================================================*/

/** @defgroup WTS_Exported_Types WTS Exported Types
  * @brief
  * @{
  */
/**
 * @brief P_FUN_WTS_SERVER_APP_CB Walkie Talkie Server Callback Function Point Definition Function
 *        pointer used in Walkie Talkie server module, to send events to specific server module.
 */
typedef T_APP_RESULT(*P_FUN_WTS_SERVER_APP_CB)(uint16_t conn_handle, uint16_t cid, uint8_t type,
                                               void *p_data);

/** @brief Walkie Talkie server write ind
 *         The message data for GATT_MSG_WTS_SERVER_WRITE.
*/
typedef struct
{
    uint16_t len;
    uint8_t *p_value;
} T_WTS_SERVER_WRITE_DATA;

/** @} End of WTS_Exported_Types */

/*============================================================================*
 *                              Functions
 *============================================================================*/

/** @defgroup WTS_Exported_Functions WTS Exported Functions
  * @brief
  * @{
  */
/**
 * @brief       Send voice data .
 *
 * @param[in]   conn_handle    Connection handle of the ACL link.
 * @param[in]   cid            Local CID assigned by Bluetooth stack.
 * @param[in]   p_data         voice data.
 * @param[in]   len            data length.
 * @return Operation result.
 * @retval true Operation success.
 * @retval false Operation failure.
 */
bool wts_send_voice_data_notify(uint16_t conn_handle, uint16_t cid, uint8_t *p_data, uint16_t len);

/**
 * @brief       Send control point data .
 *
 * @param[in]   conn_handle    Connection handle of the ACL link.
 * @param[in]   cid            Local CID assigned by Bluetooth stack.
 * @param[in]   p_data         control point data.
 * @param[in]   len            data length.
 * @return Operation result.
 * @retval true Operation success.
 * @retval false Operation failure.
 */
bool wts_send_control_point_notify(uint16_t conn_handle, uint16_t cid, uint8_t *p_data,
                                   uint16_t len);

/**
 * @brief Add walkie talkie service to the BLE stack database.
 *
 * @param[in]   app_cb  Callback when service attribute was read, write or cccd update.
 * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
 * @retval 0xFF Operation failure.
 * @retval others Service id assigned by stack.
 */

T_SERVER_ID wts_reg_srv(P_FUN_WTS_SERVER_APP_CB app_cb);

/** @} End of WTS_Exported_Functions */

/** @} End of WTS_GATT_SVC */


#ifdef  __cplusplus
}
#endif      /*  __cplusplus */

#endif //_WALKIE_TALKIE_GATT_SVC_H_
