CONFIG_SERIAL=y

# Use realtek console with uart dma 
# the dma node should be added in uart node
CONFIG_UART_ASYNC_API=y
# Use realtek console with uart interrupt
# CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_REALTEK_SUBSYS_SYSM=y
CONFIG_REALTEK_SUBSYS_CONSOLE=y
CONFIG_REALTEK_SUBSYS_REMOTE=y
CONFIG_REALTEK_SUBSYS_BTM=y
CONFIG_REALTEK_SUBSYS_AUDIO=y
CONFIG_HEAP_MEM_POOL_SIZE=1024


