/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

#include <string.h>
#include "app_audio_tone_cfg.h"
#include "app_audio_cfg.h"

const T_APP_AUDIO_TONE_CFG app_audio_tone_cfg =
{

    //.tone_power_on              = TONE_INVALID_INDEX,
    //.tone_power_off             = TONE_INVALID_INDEX,
    //.tone_pairing               = TONE_INVALID_INDEX,
    .tone_pairing_complete      = TONE_INVALID_INDEX,
    .tone_pairing_fail          = TONE_INVALID_INDEX,
    .tone_key_short_press       = TONE_INVALID_INDEX,
    .tone_key_long_press        = TONE_INVALID_INDEX,
    .tone_vol_changed           = TONE_INVALID_INDEX,
    .tone_key_hybrid            = TONE_INVALID_INDEX,
    .tone_hf_no_service         = TONE_INVALID_INDEX,
    //.tone_hf_call_in            = TONE_INVALID_INDEX,
    .tone_first_hf_call_in      = TONE_INVALID_INDEX,
    .tone_last_hf_call_in       = TONE_INVALID_INDEX,
    .tone_hf_call_active        = TONE_INVALID_INDEX,
    .tone_hf_call_end           = TONE_INVALID_INDEX,
    .tone_hf_call_reject        = TONE_INVALID_INDEX,
    .tone_hf_call_voice_dial    = TONE_INVALID_INDEX,
    .tone_hf_call_redial        = TONE_INVALID_INDEX,
    .tone_in_ear_detection      = TONE_INVALID_INDEX,
    .tone_gfps_findme           = TONE_INVALID_INDEX,
    //.tone_link_connected        = TONE_INVALID_INDEX,
    .tone_vol_max               = TONE_INVALID_INDEX,
    .tone_vol_min               = TONE_INVALID_INDEX,
    .tone_alarm                 = TONE_INVALID_INDEX,
    .tone_link_loss             = TONE_INVALID_INDEX,
    //.tone_link_disconnect       = TONE_INVALID_INDEX,
    .tone_remote_connected      = TONE_INVALID_INDEX,
    .tone_remote_role_primary   = TONE_INVALID_INDEX,
    .tone_remote_role_secondary = TONE_INVALID_INDEX,
    .tone_light_sensor_on       = TONE_INVALID_INDEX,
    .tone_light_sensor_off      = TONE_INVALID_INDEX,
    .tone_exit_gaming_mode      = TONE_INVALID_INDEX,
    .tone_enter_airplane        = TONE_INVALID_INDEX,
    .tone_ota_over_ble_start    = TONE_INVALID_INDEX,
    .tone_le_pair_complete      = TONE_INVALID_INDEX,
    .tone_pairing_timeout       = TONE_INVALID_INDEX,
    .tone_mic_mute_alarm        = TONE_INVALID_INDEX,
    .tone_key_ultra_long_press  = TONE_INVALID_INDEX,
    .tone_dev_multilink_on      = TONE_INVALID_INDEX,
    .tone_remote_disconnect     = TONE_INVALID_INDEX,
    .tone_factory_reset         = TONE_INVALID_INDEX,
    .tone_remote_loss           = TONE_INVALID_INDEX,
    .tone_mic_mute_on           = TONE_INVALID_INDEX,
    .tone_mic_mute_off          = TONE_INVALID_INDEX,
    .tone_link_loss2            = TONE_INVALID_INDEX,
    .tone_link_disconnect2      = TONE_INVALID_INDEX,
    .tone_battery_percentage_10 = TONE_INVALID_INDEX,
    .tone_battery_percentage_20 = TONE_INVALID_INDEX,
    .tone_battery_percentage_30 = TONE_INVALID_INDEX,
    .tone_battery_percentage_40 = TONE_INVALID_INDEX,
    .tone_battery_percentage_50 = TONE_INVALID_INDEX,
    .tone_battery_percentage_60 = TONE_INVALID_INDEX,
    .tone_battery_percentage_70 = TONE_INVALID_INDEX,
    .tone_battery_percentage_80 = TONE_INVALID_INDEX,
    .tone_battery_percentage_90 = TONE_INVALID_INDEX,
    .tone_battery_percentage_100 = TONE_INVALID_INDEX,
    .tone_audio_playing         = TONE_INVALID_INDEX,
    .tone_audio_paused          = TONE_INVALID_INDEX,
    .tone_audio_forward         = TONE_INVALID_INDEX,
    .tone_audio_backward        = TONE_INVALID_INDEX,
    .tone_apt_on                = TONE_INVALID_INDEX,
    .tone_apt_off               = TONE_INVALID_INDEX,
    .tone_enter_gaming_mode     = TONE_INVALID_INDEX,
    .tone_output_indication_1   = TONE_INVALID_INDEX,

    .tone_switch_vp_language    = TONE_INVALID_INDEX,
    .tone_dut_test              = TONE_INVALID_INDEX,
    .tone_hf_transfer_to_phone  = TONE_INVALID_INDEX,
    .tone_hf_outgoing_call      = TONE_INVALID_INDEX,
    .tone_audio_effect_0        = TONE_INVALID_INDEX,
    .tone_audio_effect_1        = TONE_INVALID_INDEX,
    .tone_audio_effect_2        = TONE_INVALID_INDEX,
    .tone_sound_press_calibration = TONE_INVALID_INDEX,

    .tone_exit_airplane         = TONE_INVALID_INDEX,
    .tone_anc_apt_off           = TONE_INVALID_INDEX,
    .tone_anc_scenario_1        = TONE_INVALID_INDEX,
    .tone_anc_scenario_2        = TONE_INVALID_INDEX,
    .tone_anc_scenario_3        = TONE_INVALID_INDEX,
    .tone_anc_scenario_4        = TONE_INVALID_INDEX,
    .tone_anc_scenario_5        = TONE_INVALID_INDEX,
    .tone_enter_dongle_mode     = TONE_INVALID_INDEX,

    .tone_apt_vol_0             = TONE_INVALID_INDEX,
    .tone_apt_vol_1             = TONE_INVALID_INDEX,
    .tone_apt_vol_2             = TONE_INVALID_INDEX,
    .tone_apt_volume_up         = TONE_INVALID_INDEX,
    .tone_apt_volume_down       = TONE_INVALID_INDEX,
#if CONFIG_REALTEK_FINDMY_FEATURE_SUPPORT
    .tone_find_my               = TONE_INVALID_INDEX,
#else
    .tone_audio_eq_0            = TONE_INVALID_INDEX,
#endif
    .tone_audio_eq_1            = TONE_INVALID_INDEX,
    .tone_audio_eq_2            = TONE_INVALID_INDEX,
    .tone_audio_eq_3            = TONE_INVALID_INDEX,
    .tone_audio_eq_4            = TONE_INVALID_INDEX,
    .tone_audio_eq_5            = TONE_INVALID_INDEX,
    .tone_audio_eq_6            = TONE_INVALID_INDEX,
    .tone_audio_eq_7            = TONE_INVALID_INDEX,
    .tone_audio_eq_8            = TONE_INVALID_INDEX,
    .tone_audio_eq_9            = TONE_INVALID_INDEX,
    .tone_apt_vol_max           = TONE_INVALID_INDEX,
    .tone_apt_vol_min           = TONE_INVALID_INDEX,
    .tone_apt_eq_0              = TONE_INVALID_INDEX,
    .tone_apt_eq_1              = TONE_INVALID_INDEX,
    .tone_apt_eq_2              = TONE_INVALID_INDEX,
    .tone_apt_eq_3              = TONE_INVALID_INDEX,
    .tone_apt_eq_4              = TONE_INVALID_INDEX,
    .tone_apt_eq_5              = TONE_INVALID_INDEX,
    .tone_apt_eq_6              = TONE_INVALID_INDEX,
    .tone_apt_eq_7              = TONE_INVALID_INDEX,
    .tone_apt_eq_8              = TONE_INVALID_INDEX,
    .tone_apt_eq_9              = TONE_INVALID_INDEX,
    .tone_llapt_scenario_1      = TONE_INVALID_INDEX,
    .tone_llapt_scenario_2      = TONE_INVALID_INDEX,
    .tone_llapt_scenario_3      = TONE_INVALID_INDEX,
    .tone_llapt_scenario_4      = TONE_INVALID_INDEX,
    .tone_llapt_scenario_5      = TONE_INVALID_INDEX,
    .tone_ama_start_speech      = TONE_INVALID_INDEX,
    .tone_ama_stop_speech       = TONE_INVALID_INDEX,
    .tone_ama_error_indication  = TONE_INVALID_INDEX,
    .tone_apt_vol_3             = TONE_INVALID_INDEX,
    .tone_apt_vol_4             = TONE_INVALID_INDEX,
    .tone_apt_vol_5             = TONE_INVALID_INDEX,
    .tone_apt_vol_6             = TONE_INVALID_INDEX,
    .tone_apt_vol_7             = TONE_INVALID_INDEX,
    .tone_apt_vol_8             = TONE_INVALID_INDEX,
#if CONFIG_REALTEK_GFPS_LE_DEVICE_SUPPORT
    .gfps_pairing_tone          = TONE_INVALID_INDEX,
#else
    .tone_apt_vol_9             = TONE_INVALID_INDEX,
#endif
    .tone_bis_start             = TONE_INVALID_INDEX,
    .tone_bis_stop              = TONE_INVALID_INDEX,
    .tone_cis_start             = TONE_INVALID_INDEX,
    .tone_cis_timeout           = TONE_INVALID_INDEX,
    .tone_cis_simu              = TONE_INVALID_INDEX,
    .tone_bis_loss              = TONE_INVALID_INDEX,

    //Tone2: 32 bytes (offset 0x3B0)
    .cis_loss                   = TONE_INVALID_INDEX,
    .cis_connected              = TONE_INVALID_INDEX,
    .tone_gfps_dult_find        = TONE_INVALID_INDEX,
    //.tone_reserved[29] = {TONE_INVALID_INDEX},

    .tone_link_connected    = 0x8c,
    .tone_hf_call_in        = 0x8d,
    .tone_pairing           = 0x90,
    .tone_link_disconnect   = 0x97,
    .tone_power_off         = 0x9b,
    .tone_power_on          = 0x9c,
};
