/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

/*============================================================================*
 *                      Define to prevent recursive inclusion
 *============================================================================*/
#ifndef _PLAYBACK_SERVICE_H_
#define _PLAYBACK_SERVICE_H_

#ifdef __cplusplus
extern "C" {
#endif

/*============================================================================*
 *                              Header Files
 *============================================================================*/
#include "bt_gatt_svc.h"
#include "app_msg.h"

/** @defgroup  PLAYBACK_SERVICE PLAYBACK Service
    * @brief LE Service to implement PLAYBACK feature
    * @{
    */

#define BLE_PLAYBACK_MTU_SIZE   0x80

/** @defgroup PLAYBACK_SVC_CB_MSG
  * @brief PLAYBACK server callback messages
  * @{
  */
#define GATT_MSG_PLAYBACK_SERVER_WRITE             0x00
#define GATT_MSG_PLAYBACK_SERVER_CCCD_UPDATE       0x01
/** @} End of PLAYBACK_SVC_CB_MSG */

/*============================================================================*
 *                              Types
 *============================================================================*/
/** @defgroup PLAYBACK_SERVICE_Exported_Types PLAYBACK Service Exported Types
    * @brief
    * @{
    */

/**
 * @brief P_FUN_PLAYBACK_SERVER_APP_CB PLAYBACK Server Callback Function Point Definition Function
 *        pointer used in PLAYBACK server module, to send events to specific server module.
 *        The events @ref PLAYBACK_SVC_CB_MSG.
 */
typedef uint16_t (*P_FUN_PLAYBACK_SERVER_APP_CB)(uint8_t type, void *p_data);

/** @brief  PLAYBACK write message */
typedef struct
{
    uint8_t opcode;
    uint8_t value;
} T_PLAYBACK_WRITE_MSG;

/** @brief  PLAYBACK upstream message data */
typedef union
{
    uint8_t notification_indification_index;
    uint8_t read_value_index;
    T_PLAYBACK_WRITE_MSG write;
} T_PLAYBACK_UPSTREAM_MSG_DATA;


/** @brief  PLAYBACK service callback data to inform application */
typedef struct
{
    uint8_t                     conn_id;
    uint16_t                    conn_handle;
    uint16_t                    cid;
    T_GAP_CHANN_TYPE            chann_type;
    T_PLAYBACK_UPSTREAM_MSG_DATA     msg_data;
} T_PLAYBACK_CALLBACK_DATA;

/** End of PLAYBACK_SERVICE_Exported_Types
    * @}
    */

/*============================================================================*
 *                              Macros
 *============================================================================*/
/** @defgroup PLAYBACK_SERVICE_Exported_Macros PLAYBACK service Exported Macros
    * @brief
    * @{
    */

/** @brief  vendor UUID defined for playback service*/
#define  GATT_UUID128_PLAYBACK_SERVICE_ADV   0xF5, 0x17, 0x82, 0x91, 0x82, 0x67, 0x42, 0x6C, 0xBD, 0xA1, 0x70, 0x4A, 0xA9, 0x58, 0x4D, 0x49

/** @brief  Demo Profile service related UUIDs. */
#define GATT_UUID_CHAR_PLAYBACK_WRITE                          0xBA26
#define GATT_UUID_CHAR_PLAYBACK_NOTIFY                         0xBA27

/** @brief  Index of each characteristic in Demo Profile service database. */
#define BLE_SERVICE_CHAR_PLAYBACK_WRITE_INDEX                   0x02
#define BLE_SERVICE_CHAR_PLAYBACK_NOTIFY_INDEX                  0x04
#define BLE_SERVICE_CHAR_PLAYBACK_DATA_CCCD_INDEX               0x05 /**< @brief Index for Transmit Service tx chars's CCCD value */

/** End of PLAYBACK_SERVICE_Exported_Macros
    * @}
    */

/*============================================================================*
 *                              Functions
 *============================================================================*/
/** @defgroup PLAYBACK_SERVICE_Exported_Functions PLAYBACK service Exported Functions
    * @brief
    * @{
    */

/**
    * @brief    Add PLAYBACK BLE service to application
    * @param    app_cb  Callback when service attribute was read, write or cccd update.
    * @return   Service ID auto generated by profile layer
    * @retval   A T_SERVER_ID type value
    */
T_SERVER_ID playback_reg_srv(P_FUN_PLAYBACK_SERVER_APP_CB app_cb);

/**
    * @brief    Send notification to peer side
    * @param    conn_handle   Connection handle identifying the BLE link.
    * @param    cid           Characteristic ID used to specify the attribute for notification.
    * @param    p_data  value to be send to peer
    * @param    data_len  data length of the value to be send
    * @return   void
    */
void playback_service_send_notification(uint16_t conn_handle, uint16_t cid, uint8_t *p_data,
                                        uint16_t data_len);

/**
    * @brief    Write characteristic data from service
    * @param    conn_handle   Connection handle identifying the BLE link.
    * @param    cid           Characteristic ID used to specify the attribute for notification.
    * @param    service_id   Service ID to be written
    * @param    attr_index  Attribute index of characteristic
    * @param    write_type  Write type of data to be written
    * @param    length      Length of value to be written
    * @param    p_value     Value to be written
    * @param    p_write_ind_post_proc   Write indicate post procedure
    * @return   T_APP_RESULT
    * @retval   Profile procedure result
    */
static T_APP_RESULT playback_service_attr_write_cb(uint16_t conn_handle, uint16_t cid,
                                                   T_SERVER_ID service_id,
                                                   uint16_t attr_index,
                                                   T_WRITE_TYPE write_type,
                                                   uint16_t length, uint8_t *p_value,
                                                   P_FUN_EXT_WRITE_IND_POST_PROC *p_write_ind_post_proc);
/**
    * @brief    Write characteristic data from service
    * @param    conn_handle   Connection handle identifying the BLE link.
    * @param    cid           Characteristic ID used to specify the attribute for notification.
    * @param    service_id   Service ID to be written
    * @param    attr_index  Attribute index of characteristic
    * @param    cccd_bits  cccd value
    * @return   void
    */
void playback_cccd_update_cb(uint16_t conn_handle, uint16_t cid, T_SERVER_ID service_id,
                             uint16_t attrib_idx,
                             uint16_t cccd_bits);

/** End of PLAYBACK_SERVICE_Exported_Functions
    * @}
    */

/*============================================================================*
 *                              Variables
 *============================================================================*/
extern T_SERVER_ID srv_id_local;

/*============================================================================*
 *                              Functions
 *============================================================================*/

/**
 * @brief  GATT callback for playback service (defined in playback_service.c)
 */
extern T_APP_RESULT playback_gatt_svc_callback(uint8_t type, void *p_data);

/** End of PLAYBACK_SERVICE
    * @}
    */
#ifdef __cplusplus
}
#endif

#endif
