#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

#################HoneyGUI Config###############################
CONFIG_REALTEK_HONEYGUI=y
CONFIG_REALTEK_APP_GUI=y

#################Realtek Display Config########################
CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y
CONFIG_REALTEK_DISPLAY_GUI_ACC=y
CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI=y
CONFIG_REALTEK_TOUCH_CHSC6417_ZEPHYR=y

CONFIG_STATIC_INIT_GNU=y
###############end build option#############################
