[ic_info]
ic_type = IC_87X3EP   ; IC_8763B_V3,IC_8763C_V2,IC_8763C_V1,IC_87X3EP
img_hdr_size = 0x400 ; image header size

[uart_property]
default_open_baudrate = 115200  ; for 2w, it's 115200, for 1w, it's 2000000
default_modify_baudrate = 1000000 ; only valid for 2w

[data uart timeout]
wait_for_load_rp_s = 0.11

[flash setting]
flash_address_non_cache_mask = 0x0  ;0x0:don't need to adjust address, 0x1000000: non-cache mask

occd_img_addr = 0x02002000  ; non-cache flash address
occd_img_size = 0x2000
flash_protection_start_addr = 0 ; non-cache flash address
flash_protection_end_addr = 0  ; non-cache flash address
flash_size = 0x8000000 ; 0x400000

[dbg board sleep time]
dbg_board_wait_for_console_s = 0.02 ; second, for easy mode,wait for \r\n
wait_to_enter_hci_mode_s = 9  ; wait for target device to enter into hci mode

[app cli]
app_cli_uart_baudrate = 2000000
detect_app_state_time_s = 15 ; second, dynamically wait for application cli through \r
wait_for_enter_console_s = 0.01 ;second, wait for \r
cli_read_timeout_ms = 200

;used for ic 8763C / 8763D
[handshake setting]
log_enable = 0xFF ; log enable: 0xFF, log disable: 0
read_timeout_ms = 10 ; handshake response read timeout ms
handshake_timeout_s = 300 ; unit second
is_reboot = False ; True:reboot before handshake, False:don't reboot
reboot_type = 1 ; 0: hci reboot, 1:bud reboot\r

;only for ic 8763C V2
[update ram patch]
enable = True
ram_path =  RTL87X3EP_V0_FW.bin
[packet size]
2w_packet_size = 0x4000
1w_packet_size = 0x1000
;only for ic 8763C / 8763D
[spic select]
spic_select_number = 0
spic_select_try_times_max = 10



