#################Zephyr Filesystem Config########################
#zephyr fs config
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_DISK_DRIVER_FLASH_RTK=n
CONFIG_FILE_SYSTEM_ROMFS=n
#fat fs config
CONFIG_FS_FATFS_LFN_MODE_HEAP=y
CONFIG_FS_FATFS_REENTRANT=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_CODEPAGE=437
CONFIG_FS_FATFS_MAX_SS=512
CONFIG_FS_FATFS_MOUNT_MKFS=n
# 2 for music player header and name files
# 2 for record header and name files
# 1 for honey gui
# 1 for other files
CONFIG_FS_FATFS_NUM_FILES=8

#################Realtek System Config########################
#power manager
CONFIG_PM=y

#hard fault output by Zephyr or by Realtek
CONFIG_DSP_SHARE_RAM_80K=y

#################Realtek Subsys Config########################
CONFIG_REALTEK_SUBSYS_BTM=y
CONFIG_REALTEK_SUBSYS_AUDIO=y
CONFIG_REALTEK_SUBSYS_CONSOLE=y
CONFIG_REALTEK_SUBSYS_REMOTE=y
CONFIG_REALTEK_SUBSYS_SYSM=y
CONFIG_REALTEK_SUBSYS_BLE_MGR=y
CONFIG_REALTEK_SUBSYS_GATT_PROFILE_ANCS_CLIENT=y
CONFIG_REALTEK_SUBSYS_GATT_PROFILE_BAS_SERVER=y
CONFIG_REALTEK_SUBSYS_GATT_PROFILE_DIS_SERVER=y
#################Realtek Watch Application Config########################
#watch app config

#eq config
CONFIG_EQ=y

#BT CTKD config
CONFIG_SC_KEY_DERIVE=n

#GATT over BR/EDR config
CONFIG_GATT_OVER_BREDR=n

#Airsync config
CONFIG_AIRSYNC_SERVICE_SUPPORT=n
CONFIG_AIRSYNC_GATT_OVER_BREDR=n

#local playback config
CONFIG_LOCAL_PLAYBACK=y
CONFIG_PLAYBACK_GATT_OVER_BREDR=n

#dfu config
CONFIG_DFU=y

#opus config
CONFIG_OPUS=n

#mfb config
CONFIG_MFB=y

#findmy config
CONFIG_FINDMY=n
CONFIG_REALTEK_SUBSYS_GATT_PROFILE_TPS_SERVER=n
CONFIG_REALTEK_SUBSYS_MBEDTLS=n

#charger config
# CONFIG_HUB_CHARGER and CONFIG_INTERNAL_CHARGER are mutually exclusive, only one of them can be enabled at the same time.
CONFIG_HUB_CHARGER=y
CONFIG_CJ4056_CHARGER=n
CONFIG_INTERNAL_CHARGER=y

#ppg config
# ppg function need to enable gsensor
CONFIG_HUB_GSENSOR=n
CONFIG_HUB_HRS=n
CONFIG_REALTEK_SUBSYS_GATT_PROFILE_HRS_SERVER=n

#walkie talkie config
CONFIG_WALKIE_TALKIE=n

#wechat call config
CONFIG_WECHAT_CALL_ON_PHONE_OUTPUT_ONLY=n

#gfps config
CONFIG_REALTEK_GFPS_FEATURE_SUPPORT=n

#wifi config
# CONFIG_SDHC and CONFIG_SDIO_STACK are required by wifi sdio driver
# CONFIG_SERIAL and CONFIG_UART_ASYNC_API are required by wifi uart driver
# CONFIG_PINCTRL_DYNAMIC is required by wifi program driver to support dynamic pinctrl configuration
CONFIG_WIFI=n
CONFIG_SDHC=n
CONFIG_SDIO_STACK=n
CONFIG_SERIAL=n
CONFIG_UART_ASYNC_API=n
CONFIG_PINCTRL_DYNAMIC=n

# CONFIG_REALTEK_KEY_BUTTON_8773G_ZEPHYR not totally decoupled with module/display
# it compiles in realtek_display_driver_library, so we have to set CONFIG_REALTEK_DISPLAY=y
# the rest gui related config moved to realtek-app/snippets/gui
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_KEY_BUTTON_8773G_ZEPHYR=y


