# LVGL framework core
CONFIG_REALTEK_HONEYGUI=n
CONFIG_REALTEK_BUILD_LVGL=y
CONFIG_LV_CONF_SKIP=n

# LVGL apps / demos
CONFIG_REALTEK_BUILD_LVGL_SIMPLE_DEMO=y
CONFIG_REALTEK_BUILD_LVGL_RTK_DEMO=y
CONFIG_LV_BUILD_DEMOS=y
CONFIG_LV_USE_DEMO_BENCHMARK=y
CONFIG_LV_USE_DEMO_MUSIC=y
CONFIG_LV_USE_DEMO_STRESS=y
CONFIG_LV_USE_DEMO_WIDGETS=y
CONFIG_REALTEK_BUILD_GUI_410_502_LVGL_DEMO=n
CONFIG_REALTEK_BUILD_GUI_410_502_SQUARELINE_DEMO=n

# LVGL lite3d
CONFIG_REALTEK_BUILD_LVGL_LITE3D=y
CONFIG_REALTEK_BUILD_LVGL_LITE3D_8773G_ZEPHYR_LIB=y

# LVGL freetype
CONFIG_REALTEK_BUILD_FREETYPE_SRC=n
CONFIG_FREETYPE_USE_LVGL_PORT=n

# Display common
CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y

# Screen + touch (410_502 + CHSC6417)
CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI=y
CONFIG_REALTEK_TOUCH_CHSC6417_ZEPHYR=y

# C++ language support
CONFIG_CPP=y
CONFIG_STD_CPP11=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y
