/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

/*============================================================================*
 *                      Define to prevent recursive inclusion
 *============================================================================*/
#ifndef _DFU_SERVICE_H_
#define _DFU_SERVICE_H_

#ifdef __cplusplus
extern "C" {
#endif

/*============================================================================*
 *                              Header Files
 *============================================================================*/
#include "bt_gatt_svc.h"
#include "app_msg.h"

/** @defgroup  OTA_SERVICE OTA Service
    * @brief LE Service to implement OTA feature
    * @{
    */
/*============================================================================*
 *                              Macros
 *============================================================================*/
/** @defgroup OTA_SERVICE_Exported_Macros OTA service Exported Macros
    * @brief
    * @{
    */
#define  BLE_GATT_UUID128_DFU_SERVICE       0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x87, 0x62, 0x00, 0x00
#define  BLE_GATT_UUID128_DFU_PACKET        0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x87, 0x63, 0x00, 0x00
#define  BLE_GATT_UUID128_DFU_CONTROL_POINT 0x12, 0xA2, 0x4D, 0x2E, 0xFE, 0x14, 0x48, 0x8e, 0x93, 0xD2, 0x17, 0x3C, 0x87, 0x64, 0x00, 0x00

#define INDEX_DFU_CHAR_DFU_PACKET_INDEX           0x2
#define INDEX_DFU_CHAR_DFU_CONTROL_POINT_INDEX    0x4
#define INDEX_DFU_CHAR_DFU_CP_CCCD_INDEX          0x5


#define DFU_CP_NOTIFY_ENABLE    0x1
#define DFU_CP_NOTIFY_DISABLE   0x2

/** @defgroup DFU_SVC_CB_MSG
  * @brief DFU server callback messages
  * @{
  */
#define GATT_MSG_DFU_SERVER_WRITE          0x00
#define GATT_MSG_DFU_SERVER_CCCD_UPDATE    0x01
/** @} End of DFU_SVC_CB_MSG */

/** End of OTA_SERVICE_Exported_Macros
    * @}
    */

/*============================================================================*
 *                              Types
 *============================================================================*/
/** @defgroup OTA_SERVICE_Exported_Types OTA Service Exported Types
    * @brief
    * @{
    */

/**
 * @brief P_FUN_DFU_SERVER_APP_CB DFU Server Callback Function Point Definition Function
 *        pointer used in DFU server module, to send events to specific server module.
 *        The events @ref DFU_SVC_CB_MSG.
 */
typedef uint16_t (*P_FUN_DFU_SERVER_APP_CB)(uint8_t type, void *p_data);

/** @brief  OTA write message */
typedef struct
{
    uint8_t opcode;
    uint8_t value;
} T_DFU_WRITE_MSG;

/** @brief  OTA upstream message data */
typedef union
{
    uint8_t notification_indification_index;
    T_DFU_WRITE_MSG write;
} T_DFU_UPSTREAM_MSG_DATA;


/** @brief  OTA service callback data to inform application */
typedef struct
{
    T_SERVER_ID                 service_id;
    uint8_t                     conn_id;
    uint16_t                    conn_handle;//gatt extend api? conn_handle?cid
    uint16_t                    cid;
    T_DFU_UPSTREAM_MSG_DATA  msg_data;
} T_DFU_CALLBACK_DATA;

/** End of OTA_SERVICE_Exported_Types
    * @}
    */

/*============================================================================*
 *                              Functions
 *============================================================================*/
/** @defgroup OTA_SERVICE_Exported_Functions OTA service Exported Functions
    * @brief
    * @{
    */

/**
    * @brief    Add OTA BLE service to application
    * @param    app_cb  Callback when service attribute was read, write or cccd update.
    * @return   Service ID auto generated by profile layer
    * @retval   A T_SERVER_ID type value
    */
T_SERVER_ID dfu_reg_srv(P_FUN_DFU_SERVER_APP_CB app_cb);

/**
    * @brief    Send notification to peer device.
    * @param    conn_handle  Connection handle identifying the BLE link.
    * @param    cid          Characteristic ID (CID) specifying the attribute to notify.
    * @param    p_data       Pointer to the data buffer to be sent as notification.
    * @param    data_len     Length of the data to be sent.
    * @return   void
 */
void dfu_service_send_notification(uint16_t conn_handle, uint16_t cid, uint8_t *p_data,
                                   uint16_t data_len);

/** End of OTA_SERVICE_Exported_Functions
    * @}
    */

/** End of OTA_SERVICE
    * @}
    */
#ifdef __cplusplus
}
#endif

#endif
