#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#
message(STATUS "CMAKELIST FOLDER: ${CMAKE_CURRENT_SOURCE_DIR}")

if(CONFIG_ALIPAY)
    add_subdirectory(alipay)
    target_include_directories(app PRIVATE alipay)
endif()
if(CONFIG_REALTEK_SUBSYS_CONSOLE)
    add_subdirectory(console)
    target_include_directories(app PRIVATE console)
endif()
if(CONFIG_CYWEE_MOTION_ALGORITHM)
    add_subdirectory(cywee)
    target_include_directories(app PRIVATE cywee)
endif()
if(CONFIG_DFU)
    add_subdirectory(dfu)
    target_include_directories(app PRIVATE dfu)
endif()
if(CONFIG_FINDMY)
    add_subdirectory(findmy)
    target_include_directories(app PRIVATE findmy)
endif()
if(CONFIG_LOCAL_PLAYBACK)
    add_subdirectory(local_playback)
    target_include_directories(app PRIVATE local_playback)
endif()
if(CONFIG_AIRSYNC_SERVICE_SUPPORT)
    add_subdirectory(airsync)
    target_include_directories(app PRIVATE airsync)
endif()
if(CONFIG_RTK_PPG)
    add_subdirectory(rtk_ppg)
    target_include_directories(app PRIVATE rtk_ppg)
endif()
if(CONFIG_WIFI)
    add_subdirectory(wifi)
    target_include_directories(app PRIVATE wifi)
endif()
if(CONFIG_WIFI_8711)
    add_subdirectory(wifi_8711)
    target_include_directories(app PRIVATE wifi_8711)
endif()
if(CONFIG_EQ)
    add_subdirectory(eq)
    target_include_directories(app PRIVATE eq)
endif()
if(CONFIG_OPUS)
    add_subdirectory(opus)
    target_include_directories(app PRIVATE opus)
endif()
if(CONFIG_WALKIE_TALKIE)
    add_subdirectory(walkie_talkie)
    target_include_directories(app PRIVATE walkie_talkie)
endif()
if(CONFIG_CHATGPT)
    add_subdirectory(chatgpt)
    target_include_directories(app PRIVATE chatgpt)
endif()
target_include_directories(app PRIVATE algo)
if(CONFIG_REALTEK_GFPS_FEATURE_SUPPORT)
    add_subdirectory(gfps)
    target_include_directories(app PRIVATE gfps)
endif()

add_subdirectory(audio)
target_include_directories(app PRIVATE audio)
add_subdirectory(clk)
target_include_directories(app PRIVATE clk)
add_subdirectory(fs)
target_include_directories(app PRIVATE fs)
add_subdirectory(utils)
target_include_directories(app PRIVATE utils)
