#hardware device config
CONFIG_GPIO=y
CONFIG_GPIO_ENABLE_DISABLE_INTERRUPT=y
CONFIG_I2C=y

CONFIG_MAIN_STACK_SIZE=2048 
CONFIG_IDLE_STACK_SIZE=1024
CONFIG_HEAP_MEM_POOL_SIZE=2048 
#display repo config, may need to refine
CONFIG_REALTEK_HONEYGUI=y
CONFIG_REALTEK_BUILD_GUI_BOX2D=y
CONFIG_REALTEK_BUILD_GUI_410_502_DEMO=n
CONFIG_REALTEK_BUILD_EXAMPLE_IMAGE_WIDGET=y
CONFIG_REALTEK_BUILD_LITE3D=y
CONFIG_REALTEK_H264_DECODER=n
CONFIG_REALTEK_H264BSD=n
#display repo config, may need to refine
CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_GUI_ACC=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y

CONFIG_REALTEK_LCD_SH8601Z_410_502_QSPI=y
CONFIG_REALTEK_TOUCH_CHSC6417_ZEPHYR=y
CONFIG_REALTEK_KEY_BUTTON_8773G_ZEPHYR=y

# Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=n
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

#
# C++ Language Support
#
CONFIG_CPP=y
CONFIG_STD_CPP11=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y

# end of C++ Language Support

