# Honeygui framework core
CONFIG_REALTEK_HONEYGUI=y
CONFIG_REALTEK_BUILD_LVGL=n

CONFIG_REALTEK_BUILD_GUI_BOX2D=y
CONFIG_REALTEK_BUILD_LITE3D=y
CONFIG_REALTEK_H264_DECODER=y

# Display common
CONFIG_DISPLAY=y
CONFIG_REALTEK_DISPLAY=y
CONFIG_REALTEK_DISPLAY_ENABLE_LCDC=y
CONFIG_REALTEK_DISPLAY_ENABLE_PPE=y
CONFIG_REALTEK_DISPLAY_ENABLE_IDU=y
CONFIG_REALTEK_DISPLAY_ENABLE_JPU=y
CONFIG_REALTEK_DISPLAY_GUI_ACC=y

# C++ language support (honeygui depends)
CONFIG_CPP=y
CONFIG_STD_CPP11=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_GLIBCXX_LIBCPP=y
